### ISSUE TITLE
Cloudshell CR relationship with created pod doesn't work

### ISSUE THREAD

**Issue by edu-diaz** [cloudtty/cloudtty#365]
Hi again team!

First of all I would like to clarify how I do expect this to work because maybe I did wrong assumptions:

1. I expect that when I create a cloudshell CR, a pod is created and controlled by the CR.
2. I expect that when I delete the pod, the CR should recreate the pod again.
3. I expect that when I delete the CR, the pod should be deleted alongside the CR.

The thing is that I am facing the following behavior:

1. When I create a cloudshell CR, a pod is created.
2. When I delete the pod, the CR doesn't create another pod.
3. When I delete the CR, the pod keeps running.

I am using latest cloudtty 0.6.2 version. This is the evidence for behavior 2:

```
eduardo.diaz@raspi-1:~ $ cat cloudshell.yml 
apiVersion: cloudshell.cloudtty.io/v1alpha1
kind: CloudShell
metadata:
  name: cloudshell
  namespace: "cloudtty"
spec:
 secretRef:
   name: "kube-config"
 exposureMode: "NodePort"
eduardo.diaz@raspi-1:~ $ k apply -f cloudshell.yml 
cloudshell.cloudshell.cloudtty.io/cloudshell created
eduardo.diaz@raspi-1:~ $ k get cloudshell,pod -n cloudtty
NAME                                           USER   COMMAND   TYPE       URL      PHASE   AGE
cloudshell.cloudshell.cloudtty.io/cloudshell          bash      NodePort   :30485   Ready   10s

NAME                                               READY   STATUS    RESTARTS       AGE
pod/cloudtty-controller-manager-69b8c74799-qtxw9   1/1     Running   8 (2d7h ago)   13d
pod/cloudshell-worker-7sxhhztp79                   1/1     Running   0              6s
eduardo.diaz@raspi-1:~ $ k delete pod -n cloudtty cloudshell-worker-7sxhhztp79 
pod "cloudshell-worker-7sxhhztp79" deleted
eduardo.diaz@raspi-1:~ $ k get cloudshell,pod -n cloudtty
NAME                                           USER   COMMAND   TYPE       URL      PHASE   AGE
cloudshell.cloudshell.cloudtty.io/cloudshell          bash      NodePort   :30485   Ready   93s

NAME                                               READY   STATUS    RESTARTS       AGE
pod/cloudtty-controller-manager-69b8c74799-qtxw9   1/1     Running   8 (2d7h ago)   13d
```

And this is the evidence for behavior 3:

```eduardo.diaz@raspi-1:~ $ cat cloudshell.yml 
apiVersion: cloudshell.cloudtty.io/v1alpha1
kind: CloudShell
metadata:
  name: cloudshell
  namespace: "cloudtty"
spec:
 secretRef:
   name: "kube-config"
 exposureMode: "NodePort"
eduardo.diaz@raspi-1:~ $ k apply -f cloudshell.yml 
cloudshell.cloudshell.cloudtty.io/cloudshell created
eduardo.diaz@raspi-1:~ $ k get cloudshell,pod -n cloudtty
NAME                                           USER   COMMAND   TYPE       URL      PHASE   AGE
cloudshell.cloudshell.cloudtty.io/cloudshell          bash      NodePort   :32041   Ready   8s

NAME                                               READY   STATUS    RESTARTS       AGE
pod/cloudtty-controller-manager-69b8c74799-qtxw9   1/1     Running   8 (2d7h ago)   13d
pod/cloudshell-worker-jdmh7gc47n                   1/1     Running   0              5s
eduardo.diaz@raspi-1:~ $ k delete cloudshells.cloudshell.cloudtty.io -n cloudtty cloudshell 
cloudshell.cloudshell.cloudtty.io "cloudshell" deleted
eduardo.diaz@raspi-1:~ $ k get cloudshell,pod -n cloudtty
NAME                                               READY   STATUS    RESTARTS       AGE
pod/cloudtty-controller-manager-69b8c74799-qtxw9   1/1     Running   8 (2d7h ago)   13d
pod/cloudshell-worker-jdmh7gc47n                   1/1     Running   0              23s
```

Is this the expected behavior or am I doing wrong assumptions? Thank you team!

**Comment by calvin0327** [comment]
@edu-diaz Thanks for pointing out it. 

In the previous version, cloudshell works according to your assumptions. But there is a problem with this in our production environment: a pod is created when a cloudshell is created, which takes a long time.

So to shorten the cloudshell window opening time, we implemented a worker pool to cache pods. It is similar to the concept of thread pools. That's why you're looking at a scene like this.

**Comment by edu-diaz** [comment]
@calvin0327 thanks for the clarification, however I am still not sure about how does exactly the "thread pool behavior" work. Could you please share more details about it so I can have a better understanding? Thanks in advance!
